---
title: "matching_updated_icpw"
output: html_document
date: "2025-07-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Import Functions, Data, and Libraries

```{r}
devtools::load_all()
rawdat <- cleanraw(mo_map_raw) 
alldat <- rawdat |> pwide(handle_dups = "high")
bdat <- alldat$base
odat <- alldat$out
newdat <- alldat$dat
```


# Balance for Matching w/ Location V1

```{r}
dat1 <- build_analysis_sets(out_data = newdat, orig_matched_data = matdat_loc)$cc

b_covs = list("ASSESS_SCORE", "NCES_PUBLIC_PCTFRLUNCH_ROUNDED",
              "GENDER_MALE", "GENDER_FEMALE",
              "ETHNICITY_White", "ETHNICITY_Hispanic",
              "ETHNICITY_Black", "ETHNICITY_Other", "URBAN_LOC_21")
balance_w(dat1, .b_covs = b_covs, .weight = "w_final")
cat("\n")
for (i in levels(dat1$GRADE)) {
  cat("Grade: ", i, "\n")
  balance_w(dat1 |> dplyr::filter(GRADE == i), .b_covs = b_covs, .weight = "w_final")
  cat("\n")
}
```


# Balance for Matching w/ Location V3

```{r}
dat2 <- build_analysis_sets(out_data = newdat, orig_matched_data = matdat_loc3)$cc

b_covs = list("ASSESS_SCORE", "NCES_PUBLIC_PCTFRLUNCH_ROUNDED",
              "GENDER_MALE", "GENDER_FEMALE",
              "ETHNICITY_White", "ETHNICITY_Hispanic",
              "ETHNICITY_Black", "ETHNICITY_Other", "URBAN_LOC_21")
balance_w(dat2, .b_covs = b_covs, .weight = "w_final")
cat("\n")
for (i in levels(dat2$GRADE)) {
  cat("Grade: ", i, "\n")
  balance_w(dat2 |> dplyr::filter(GRADE == i), .b_covs = b_covs, .weight = "w_final")
  cat("\n")
}
```


# Balance for Matching w/ Location V1 (but exact matching in Grade 2)

```{r}
dat3 <- build_analysis_sets(out_data = newdat, orig_matched_data = matdat_mixed)$cc

b_covs = list("ASSESS_SCORE", "NCES_PUBLIC_PCTFRLUNCH_ROUNDED",
              "GENDER_MALE", "GENDER_FEMALE",
              "ETHNICITY_White", "ETHNICITY_Hispanic",
              "ETHNICITY_Black", "ETHNICITY_Other", "URBAN_LOC_21")
balance_w(dat3 , .b_covs = b_covs, .weight = "w_final")
cat("\n")
for (i in levels(dat3 $GRADE)) {
  cat("Grade: ", i, "\n")
  balance_w(dat3 |> dplyr::filter(GRADE == i), .b_covs = b_covs, .weight = "w_final")
  cat("\n")
}
```


## Export Matched Data to Excel

```{r}
#List Export Objects
updated_matched_ipcw <- list("rawdat" = rawdat,
                "formatted_rawdat" = newdat,
                "Location_V1" = dat1,
                "Location_V3" = dat2,
                "Location_V1_exact_Gr2" = dat3
                )

#Export to Excel
writexl::write_xlsx(updated_matched_ipcw, "updated_matched_ipcw.xlsx")
```
