globalVariables(c(
  "mo_map_fall24","DISTRICT_BUSINESS_IDENTIFIER", "treatment_district",
  "GRADE", "MPG_TEST_YN", "ASSESS_STD_ERR", "ASSESS_SCORE", "ASSESS_SCORE_fmean",
  "ASSESS_SCORE_fsd", "NWEA_ETHNIC_GROUP_NAME", "STUDENT_GENDER", "ETHNICITY",
  "ETHNICITY_White", "ETHNICITY_Black", "ETHNICITY_Hispanic", "NCES_PUBLIC_URBAN_LOC_CODE",
  "URBAN_LOC_41", "URBAN_LOC_21", "LOC", "GRADE", "treat", "NCES_PUBLIC_PCT_TOTAL_BLACK_ROUNDED",
  "NCES_PUBLIC_PCT_TOTAL_HISPANIC_ROUNDED", "NCES_PUBLIC_PCT_TOTAL_WHITE_ROUNDED",
  "STUDENT_BUSINESS_IDENTIFIER", "TERM_NUMBER"
))
